spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${naver-id}
            client-secret: ${naver-secret}
            authorization-grant-type: authorization_code
            client-name: independe
            redirect-uri: http://localhost:8080/oauth2/login/oauth2/code/naver
            scope:
          kakao:
            client-id: ${kakao-id}
            client-secret: ${kakao-secret}
            clientAuthenticationMethod: POST
            authorization-grant-type: authorization_code
            client-name: Independe
            redirect-uri: http://localhost:8080/oauth2/login/oauth2/code/naver
            scope:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            # OpenID Connect 일 경우 jwkSet URI 를 가져와야 하기 때문에 필수항목
            issuerUri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id # OpenID Connect 로 인가서버와 통신하지 않을 경우
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

file:
#  dir: C:\Users\kao25\OneDrive\바탕 화면\캡ㅅ스톤\docker
  dir: /Users/choejunhyeog/Documents/project/independefile
#  dir: C:\Users\AAA\Desktop\independe\independe\docker
